Remove redundant sh quoting

diff --git a/bin/2pd b/bin/2pd
--- a/bin/2pd
+++ b/bin/2pd
@@ -2,11 +2,11 @@
 # This script is part of Martin V\"ath's archwrap project.
 
 Echo() {
-	printf '%s\n' "${*}"
+	printf '%s\n' "$*"
 }
 
 Fatal() {
-	Echo "${0##*/}: ${*}" >&2
+	Echo "${0##*/}: $*" >&2
 	exit 2
 }
 
@@ -41,8 +41,8 @@ usetemp=:
 case ${0##*/} in
 *ppd*)	packopt='-A/RLW';;
 esac
-while [ ${#} -gt 0 ]
-do	case ${1} in
+while [ $# -gt 0 ]
+do	case $1 in
 	--[hH]*|-h|'-?')
 		Usage 0;;
 	-L)	unpackl='-L';;
@@ -57,32 +57,32 @@ do	case ${1} in
 	-tmp)	usetemp=false;;
 	-d)	withparent='-d';;
 	--)	shift; break;;
-	-*)	packopt="${packopt} ${1}";;
+	-*)	packopt="$packopt $1";;
 	*)	break;;
 	esac
 	shift
 done
-[ ${#} -ne 0 ] || Usage
+[ $# -ne 0 ] || Usage
 
 chmod=:
-if ${uread} || ${uwrite} || ${uall}
+if $uread || $uwrite || $uall
 then	chmod=chmod
-	${uread} && ${uwrite} && uall=:
-	${uread}  && chmodarg='go-rx'
-	${uwrite} && chmodarg='go-w'
-	${uall}   && chmodarg='go-rwx'
+	$uread && $uwrite && uall=:
+	$uread  && chmodarg='go-rx'
+	$uwrite && chmodarg='go-w'
+	$uall   && chmodarg='go-rwx'
 fi
 
-currd=${PWD} || currd=
-case ${currd} in
+currd=$PWD || currd=
+case $currd in
 /*)	:;;
 *)	Fatal "cannot determine current directory"
 esac
 
 Cd() {
-	case ${1} in
-	/*)	cd "${1}" >/dev/null 2>&1 || Fatal "cd ${1} failed";;
-	*)	cd "./${1#./}" >/dev/null 2>&1 || Fatal "cd ${PWD}/${1#./} failed";;
+	case $1 in
+	/*)	cd "$1" >/dev/null 2>&1 || Fatal "cd $1 failed";;
+	*)	cd "./${1#./}" >/dev/null 2>&1 || Fatal "cd $PWD/${1#./} failed";;
 	esac
 }
 
@@ -90,30 +90,30 @@ rmdirname=
 Gosane() {
 	trap : EXIT HUP INT TERM
 	[ -z "${rmdirname:++}" ] || {
-		cd "${currd}" >/dev/null \
-		&& test -d "${rmdirname}" \
-		&& rm -rf -- "${rmdirname}" && rmdirname=
+		cd "$currd" >/dev/null \
+		&& test -d "$rmdirname" \
+		&& rm -rf -- "$rmdirname" && rmdirname=
 	}
 	trap - EXIT HUP INT TERM
 }
 
 for repack
-do	test -d "${repack}" || continue
-	repackp=`readlink -f -- "${repack}"` && [ -n "${repackp:++}" ] \
-		&& test -d "${repackp}" || Fatal "cannot resolve ${repack}"
+do	test -d "$repack" || continue
+	repackp=`readlink -f -- "$repack"` && [ -n "${repackp:++}" ] \
+		&& test -d "$repackp" || Fatal "cannot resolve $repack"
 	repackp=${repack%/*}
 	full=${repack##*/}
-	blank=${full}
+	blank=$full
 	for bl in \
 		z bz2 bz tbz2 tbz gz tgz taz dir 7z t7z lz lzm lzma \
 		xz tlz txz lrz tlr tlrz lha lzh arj arz zip jar okular rar \
 		Z BZ2 BZ TBZ2 TBZ GZ TGZ TAZ DIR 7Z T7Z LZ LZM LZMA \
 		XZ TLZ TXZ LRZ TLR TLRZ LHA LZH ARJ ARZ ZIP JAR OKULAR RAR
-	do	case ${blank} in
-		*.tar."${bl}"|*.TAR."${bl}")
+	do	case $blank in
+		*.tar."$bl"|*.TAR."$bl")
 			blank=${blank%.*.*}
 			break;;
-		*."${bl}")
+		*."$bl")
 			blank=${blank%.*}
 			break;;
 		esac
@@ -124,21 +124,21 @@ do	test -d "${repack}" || continue
 	then	rmdirname=`mktemp -d "/tmp/${0##*/}.XXXXXXXX"` \
 			&& [ -n "${rmdirname:++}" ] \
 			|| Fatal 'cannot create temporary directory'
-		unpackp=${rmdirname}
-	else	unpackp=${currd}
+		unpackp=$rmdirname
+	else	unpackp=$currd
 	fi
-	tempdirname="${unpackp}/${blank}"
-	test -r "${tempdirname}" && Fatal "${tempdirname} already exists"
-	Cd "${unpackp}"
-	u -d ${unpackx} ${unpackl} -- "${repackp}/${full}" || \
-		Fatal "cannot unpack ${repackp}/${full}"
-	Cd "${repackp}"
-	${chmod} -R -- "${chmodarg}" "${tempdirname}"
-	${renrcs} && ! test -r "${tempdirname}/RCS" \
-		&& mmv -r -- "${tempdirname}/;rcs" 'RCS'
-	tempsub=${tempdirname}
-	[ -n "${withparent:++}" ] && tempsub="${tempsub}/${blank}"
-	pd ${withparent} ${packopt} -- "${tempsub}" || \
-		Fatal "Packing ${tempsub} failed"
+	tempdirname=$unpackp/$blank
+	test -r "$tempdirname" && Fatal "$tempdirname already exists"
+	Cd "$unpackp"
+	u -d $unpackx $unpackl -- "$repackp/$full" || \
+		Fatal "cannot unpack $repackp/$full"
+	Cd "$repackp"
+	$chmod -R -- "$chmodarg" "$tempdirname"
+	$renrcs && ! test -r "$tempdirname/RCS" \
+		&& mmv -r -- "$tempdirname/;rcs" 'RCS'
+	tempsub=$tempdirname
+	[ -n "${withparent:++}" ] && tempsub=$tempsub/$blank
+	pd $withparent $packopt -- "$tempsub" || \
+		Fatal "Packing $tempsub failed"
 	Gosane
 done
diff --git a/bin/tgzd b/bin/tgzd
--- a/bin/tgzd
+++ b/bin/tgzd
@@ -88,7 +88,7 @@ case ${0##*/} in
 esac
 OPTIND=1
 while getopts 'AF@:R:SETcCfdDnbg7lLzmrtpPsXxhH?' opt
-do	case ${opt} in
+do	case $opt in
 	A)	xattr=false;;
 	F)	follow=false;;
 	S)	use_star=:;;
@@ -115,14 +115,14 @@ do	case ${opt} in
 	X)	xnames=:;;
 	x)	xnames=false;;
 	'@')	remote=r
-		remotepath=${OPTARG};;
+		remotepath=$OPTARG;;
 	R)	remote=R
-		remotepath=${OPTARG};;
+		remotepath=$OPTARG;;
 	*)	Usage 0;;
 	esac
 done
-shift $(( ${OPTIND} - 1 ))
-[ ${#} -ne 0 ] || Usage
+shift $(( $OPTIND - 1 ))
+[ $# -ne 0 ] || Usage
 
 if [ -n "${remote:++}" ]
 then	export RSH
@@ -130,9 +130,9 @@ then	export RSH
 fi
 
 Push -c taropts '-c' '-v'
-${follow} && Push taropts '-h'
+$follow && Push taropts '-h'
 
-${use_star} && unset POORTAR
+$use_star && unset POORTAR
 poortar=:
 case ${POORTAR:-n} in
 [nNfF0lL]*)
@@ -141,32 +141,32 @@ case ${POORTAR:-n} in
 	xattr=false
 	poortar=false;;
 esac
-${poortar} && xattr=false
+$poortar && xattr=false
 errfile=false
-if ${use_star}
+if $use_star
 then	tarprg='star'
 	Push taropts '-H=exustar'
 	# Push taropts '-H=pax'
-	${xattr} && Push taropts '-xattr'
-	${control} && Push taropts '-acl' '-xfflags'
+	$xattr && Push taropts '-xattr'
+	$control && Push taropts '-acl' '-xfflags'
 	#Push taropts "-dirmode"
-	${ownernum} && Push taropts '-numeric'
-	${sparse} && Push taropts '-sparse'
-	case ${comp} in
+	$ownernum && Push taropts '-numeric'
+	$sparse && Push taropts '-sparse'
+	case $comp in
 	g)	Push taropts '-z'
 		export STAR_COMPRESS_FLAG='--best';;
 	b)	Push taropts '-bz'
 		export STAR_COMPRESS_FLAG='-9';;
 	[7lr])	poortar=:;;
 	esac
-	if ! ${secmode}
-	then	"${tarprg}" -c -no-fsync >/dev/null 2>&1 && \
+	if ! $secmode
+	then	"$tarprg" -c -no-fsync >/dev/null 2>&1 && \
 			Push taropts '-no-fsync'
 	fi
 else	MakeExternal tarprg tar
-	${xattr} && Push taropts '--xattrs'
-	${ownernum} && Push taropts '--numeric-owner'
-	case ${comp} in
+	$xattr && Push taropts '--xattrs'
+	$ownernum && Push taropts '--numeric-owner'
+	case $comp in
 	g)	Push taropts '--use-compress-program' "${0%/*}/gzipbest";;
 	b)	Push taropts '--use-compress-program' "${0%/*}/bzipbest";;
 	7)	Push taropts '--use-compress-program' "${0%/*}/7zbest";;
@@ -174,13 +174,13 @@ else	MakeExternal tarprg tar
 	x)	Push taropts '--use-compress-program' "${0%/*}/xzbest";;
 	r)	poortar=:;;
 	esac
-	if ${poortar}
+	if $poortar
 	then	errfile=:
-	else	${sparse} && Push taropts '-S'
+	else	$sparse && Push taropts '-S'
 	fi
 fi
-if ${xnames}
-then	case ${comp} in
+if $xnames
+then	case $comp in
 	g)	ext='tar.gz';;
 	b)	ext='tar.bz2';;
 	7)	ext='tar.7z';;
@@ -189,7 +189,7 @@ then	case ${comp} in
 	r)	ext='tar.lrz';;
 	*)	ext='tar';;
 	esac
-else	case ${comp} in
+else	case $comp in
 	g)	ext='tgz';;
 	b)	ext='tbz';;
 	7)	ext='t7z';;
@@ -202,50 +202,50 @@ fi
 
 Tarit() {
 	if [ -z "${remote:++}" ]
-	then	archive="${d}/${name}.${1}"
-		rm -f -- "${archive}"
+	then	archive=$d/$name.$1
+		rm -f -- "$archive"
 	elif [ "$remote" = 'r' ]
-	then	archive="${remotepath}${name}.${1}"
-	else	archive="${remotepath}"
+	then	archive=$remotepath$name.$1
+	else	archive=$remotepath
 	fi
 	shift
-	Cd "${dirname}" || return
+	Cd "$dirname" || return
 	stat=0
-	if ${errfile}
-	then	MkTemp || stat=${?}
+	if $errfile
+	then	MkTemp || stat=$?
 	fi
-	if ${withparent}
-	then	if ${dotparent}
+	if $withparent
+	then	if $dotparent
 		then	Push -c topack '.'
 		else	Push -c topack "${name##*/}"
 		fi
-		Cd .. || stat=${?}
+		Cd .. || stat=$?
 	else	PushTopack || {
 			stat=2
-			Error ${stat} "not creating empty archive ${archive}"
+			Error $stat "not creating empty archive $archive"
 		}
 	fi
-	[ ${stat} -eq 0 ] && if ${errfile}
-	then	eval "\"\${tarprg}\" \"\${@}\" -f \"\${archive}\" -- ${topack} 2>\"\${tempname}\""
-	else	eval "\"\${tarprg}\" \"\${@}\" -f \"\${archive}\" -- ${topack}"
-	fi || stat=${?}
-	if ${errfile}
-	then	if test -s "${tempname}"
-		then	ErrMessage "tar of ${name} led to the following error message:"
-			cat -- "${tempname}" >&2
-			[ ${stat} -eq 0 ] && stat=2
+	[ $stat -eq 0 ] && if $errfile
+	then	eval "\"\$tarprg\" \"\$@\" -f \"\$archive\" -- $topack 2>\"\$tempname\""
+	else	eval "\"\$tarprg\" \"\$@\" -f \"\$archive\" -- $topack"
+	fi || stat=$?
+	if $errfile
+	then	if test -s "$tempname"
+		then	ErrMessage "tar of $name led to the following error message:"
+			cat -- "$tempname" >&2
+			[ $stat -eq 0 ] && stat=2
 		fi
 		RmTemp
 	fi
-	Cd "${d}" || stat=${?}
-	[ ${stat} -ne 0 ] && Error ${stat} "error occured during tar of ${name}"
+	Cd "$d" || stat=$?
+	[ $stat -ne 0 ] && Error $stat "error occured during tar of $name"
 }
 
 MainLoop() {
-	d=${PWD}
+	d=$PWD
 	for progargs
-	do	dirname=${progargs}
-		while [ "${dirname%/}" != "${dirname}" ]
+	do	dirname=$progargs
+		while [ "${dirname%/}" != "$dirname" ]
 		do	dirname=${dirname%/}
 		done
 		DoDir
@@ -254,18 +254,18 @@ MainLoop() {
 
 StripDirname() {
 	for strip in taz tgz tbz dir tlz tlrz tlr
-	do	case ${dirname} in
-		*."${strip}")
+	do	case $dirname in
+		*."$strip")
 			dirname=${dirname%.*}
 			return;;
 		esac
 	done
 	for strip in z gz bz bz2 7z t7z lz lzm lzma lrz
-	do	case ${dirname} in
-		*.tar."${strip}")
+	do	case $dirname in
+		*.tar."$strip")
 			dirname=${dirname%.*.*}
 			return;;
-		*."${strip}")
+		*."$strip")
 			dirname=${dirname%.*}
 			return;;
 		esac
@@ -275,34 +275,34 @@ StripDirname() {
 unset za lrzip
 DoDir() {
 	StripDirname
-	if [ -z "${dirname:++}" ] || ! test -d "${dirname}"
-	then	Error 2 "could not find Directory ${dirname}"
+	if [ -z "${dirname:++}" ] || ! test -d "$dirname"
+	then	Error 2 "could not find Directory $dirname"
 		return
 	fi
 	name=${dirname##*/}
 	: ${name:=_}
-	eval "set -- ${taropts}"
-	if ! ${poortar}
-	then	Tarit "${ext}" "${@}"
+	eval "set -- $taropts"
+	if ! $poortar
+	then	Tarit "$ext" "$@"
 		return
 	fi
-	Tarit tar "${@}"
+	Tarit tar "$@"
 	case ${comp:-R} in
 	R)	return;;
-	g)	gzipbest -c -- "${archive}" >"${name}.${ext}";;
-	b)	bzipbest -k -c -- "${archive}" >"${name}.${ext}";;
+	g)	gzipbest -c -- "$archive" >"$name.$ext";;
+	b)	bzipbest -k -c -- "$archive" >"$name.$ext";;
 	7)	OptExternal za 7za
-		"${za}" a -- "${name}.${ext}" "${archive}";;
-	l)	lzmabest -k -c -- "${archive}" >"${name}.${ext}";;
-	x)	xzbest -k -c -- "${archive}" >"${name}.${ext}";;
+		"$za" a -- "$name.$ext" "$archive";;
+	l)	lzmabest -k -c -- "$archive" >"$name.$ext";;
+	x)	xzbest -k -c -- "$archive" >"$name.$ext";;
 	r)	OptExternal lrzip
-		"${lrzip}" -L 9 -o "${name}.${ext}" -- "${archive}";;
+		"$lrzip" -L 9 -o "$name.$ext" -- "$archive";;
 	esac || {
-		Error ${?} "error when compressing ${archive}; keeping on disk" >&2
+		Error $? "error when compressing $archive; keeping on disk" >&2
 		return
 	}
-	rm -f -- "${archive}"
+	rm -f -- "$archive"
 }
 
-MainLoop "${@}"
+MainLoop "$@"
 Exit
diff --git a/bin/u b/bin/u
--- a/bin/u
+++ b/bin/u
@@ -55,10 +55,10 @@ case ${0##*/} in
 esac
 OPTIND=1
 while getopts 'd2:STflvtjaAXxcCnLpsPEhH?' opt
-do	case ${opt} in
+do	case $opt in
 	d)	mdir=:;;
 	2)	mdir=:
-		toname=${OPTARG};;
+		toname=$OPTARG;;
 	S)	use_star=:;;
 	T)	use_star=false;;
 	f)	force=:;;
@@ -82,25 +82,25 @@ do	case ${opt} in
 	*)	Usage 0;;
 	esac
 done
-shift $(( ${OPTIND} - 1 ))
-[ ${#} -ne 0 ] || Usage
+shift $(( $OPTIND - 1 ))
+[ $# -ne 0 ] || Usage
 
-if [ -z "${restowner}" ]
+if [ -z "$restowner" ]
 then	if [ "`id -u`" -eq 0 ]
 	then	restowner=:
 	else	restowner=false
 	fi
 fi
 
-if ${dotest}
+if $dotest
 then	show=:
 	mode='testing'
-elif ${show}
+elif $show
 then	mode='showing'
 else	mode='unpacking'
 fi
 
-${use_star} && unset POORTAR
+$use_star && unset POORTAR
 case ${POORTAR:-n} in
 [nNfF0]*)
 	verypoor=false
@@ -118,102 +118,102 @@ case ${POORTAR:-n} in
 *)
 	verypoor=:;;
 esac
-${verypoor} && semipoor=:
-${semipoor} && xzpoor=:
-${xzpoor} && use_xattr=false
+$verypoor && semipoor=:
+$semipoor && xzpoor=:
+$xzpoor && use_xattr=false
 
 Push -c taropts
-${preserve} && Push taropts '-p'
-if ${use_star}
+$preserve && Push taropts '-p'
+if $use_star
 then	tarprg='star'
 	gzipflag='-z'
 	bzipflag='-bz'
 	semipoor=:
-	${use_acl} && Push taropts '-acl'
-	${ownernum} && Push taropts '-numeric'
-	${restowner} || Push taropts '-o'
-	if ! ${caremode}
+	$use_acl && Push taropts '-acl'
+	$ownernum && Push taropts '-numeric'
+	$restowner || Push taropts '-o'
+	if ! $caremode
 	then	star -c -no-fsync >/dev/null 2>&1 && Push taropts '-no-fsync'
 	fi
-	${use_xattr} && Push taropts '-xattr'
+	$use_xattr && Push taropts '-xattr'
 else	MakeExternal tarprg tar
 	gzipflag='-z'
 	bzipflag='-j'
 	xzflag='-J'
-	if ${xzpoor}
+	if $xzpoor
 	then	lzmaflag='--lzma'
-	else	lzmaflag=${xzflag}
+	else	lzmaflag=$xzflag
 		Push taropts '--no-auto-compress'
 	fi
-	${ownernum} && Push taropts '--numeric-owner'
-	${restowner} && Push taropts '--same-owner'
-	${use_xattr} && Push taropts '--xattrs'
+	$ownernum && Push taropts '--numeric-owner'
+	$restowner && Push taropts '--same-owner'
+	$use_xattr && Push taropts '--xattrs'
 fi
 
 Push -c zipopts
-${restowner} && Push zipopts '-X'
-${lower} && Push zipopts '-L'
-${junk} && Push zipopts '-j'
+$restowner && Push zipopts '-X'
+$lower && Push zipopts '-L'
+$junk && Push zipopts '-j'
 
 Getf() {
-	f=${1}
-	test -f "${f}" && return
+	f=$1
+	test -f "$f" && return
 	for i in '' .tar .TAR
 	do	for j in \
 			z bz2 bz tbz2 tbz gz tgz taz dir 7z t7z lz lzm lzma xz \
 			tlz txz lrz tlr tlrz lha lzh arj arz zip jar apk okular rar \
 			Z BZ2 BZ TBZ2 TBZ GZ TGZ TAZ DIR 7Z T7Z LZ LZM LZMA XZ \
 			TLZ TXZ LRZ TLR TLRZ LHA LZH ARJ ARZ ZIP JAR APK OKULAR RAR
-		do	f="${1}${i}.${j}"
-			test -f "${f}" && return
+		do	f=$1$i.$j
+			test -f "$f" && return
 		done
 	done
 	return 1
 }
 
 MainLoop() {
-	currdir=${PWD}
+	currdir=$PWD
 	cddone=false
 	for progargs
-	do	${cddone} && Cd "${currdir}"
+	do	$cddone && Cd "$currdir"
 		cddone=false
-		pathname=${progargs}
-		while [ "${pathname%/}" != "${pathname}" ]
+		pathname=$progargs
+		while [ "${pathname%/}" != "$pathname" ]
 		do	pathname=${pathname%/}
 		done
 		[ -z "${pathname:++}" ] && continue
-		case ${pathname} in
+		case $pathname in
 		/*)	:;;
-		*)	pathname="${currdir}/${pathname}";;
+		*)	pathname=$currdir/$pathname;;
 		esac
-		Getf "${pathname}" && DoCases \
-			|| Error 1 "cannot find ${pathname}"
+		Getf "$pathname" && DoCases \
+			|| Error 1 "cannot find $pathname"
 	done
 }
 
 umask=
 IntoDir() {
-	${mdir} || return 0
-	d=${toname}
+	$mdir || return 0
+	d=$toname
 	[ -z "${d:++}" ] && d=${name##*/}
-	if test -d "${d}"
-	then	if ! ${force}
-		then	Error 1 "Directory ${d} already exists (try -f)"
+	if test -d "$d"
+	then	if ! $force
+		then	Error 1 "Directory $d already exists (try -f)"
 			return 1
 		fi
 	else	[ -n "${umask:++}" ] || umask=`umask -S`
-		mkdir -m "${umask}" -- "${d}" >/dev/null
+		mkdir -m "$umask" -- "$d" >/dev/null
 	fi
-	Cd "${d}"
+	Cd "$d"
 	cddone=:
 }
 
 MyErr() {
-	Error 2 "error when ${mode} ${name} (type ${typ})
+	Error 2 "error when $mode $name (type $typ)
 "
 }
 MyErrNot() {
-	Error 2 "${mode} ${name} not supported"
+	Error 2 "$mode $name not supported"
 }
 
 DoCases() {
@@ -270,15 +270,15 @@ DoCases() {
 	*)
 		return 1;;
 	esac
-	if ! ${full}
-	then	case ${name} in
+	if ! $full
+	then	case $name in
 		*.tar|*.TAR)
-			typ="tar.${typ}"
+			typ=tar.$typ
 			name=${name%.*};;
 		*.arj|*.ARJ)
-			case ${typ} in
+			case $typ in
 			gz)
-				typ="arj.${typ}"
+				typ=arj.$typ
 				name=${name%.*};;
 			esac;;
 		esac
@@ -290,238 +290,238 @@ DoCases() {
 
 unset bzip gzip lzma xz lrzip za unzip unarj lha unrar
 DoIt() {
-	case ${typ} in
+	case $typ in
 tar)
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		"${tarprg}" -x -v "${@}" -f "${f}" || MyErr;;
-	s*)	"${tarprg}" -t ${verbose} -f "${f}" || MyErr;;
+		eval "set -- $taropts"
+		"$tarprg" -x -v "$@" -f "$f" || MyErr;;
+	s*)	"$tarprg" -t $verbose -f "$f" || MyErr;;
 	t*)	MyErrNot;;
 	esac;;
 tar.gz)
 	OptExternal gzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		if ${verypoor}
-		then	"${gzip}" -d -c -- "${f}" | \
-				"${tarprg}" -x -v "${@}" -f -
-		else	"${tarprg}" -x -v ${gzipflag} "${@}" -f "${f}"
+		eval "set -- $taropts"
+		if $verypoor
+		then	"$gzip" -d -c -- "$f" | \
+				"$tarprg" -x -v "$@" -f -
+		else	"$tarprg" -x -v $gzipflag "$@" -f "$f"
 		fi;;
-	s*)	if ${verypoor}
-		then	"${gzip}" -d -c -- "${f}" | "${tarprg}" -t ${verbose} -f -
-		else	"${tarprg}" -t ${verbose} ${gzipflag} -f "${f}"
+	s*)	if $verypoor
+		then	"$gzip" -d -c -- "$f" | "$tarprg" -t $verbose -f -
+		else	"$tarprg" -t $verbose $gzipflag -f "$f"
 		fi;;
-	t*)	"${gzip}" -t -v -- "${f}";;
+	t*)	"$gzip" -t -v -- "$f";;
 	esac || MyErr;;
 tar.bz2)
 	OptExternal bzip bzip2
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		if ${verypoor}
-		then	"${bzip}" -d -k -c -- "${f}" | \
-				"${tarprg}" -x -v "${@}" -f -
-		else	"${tarprg}" -x -v ${bzipflag} "${@}" -f "${f}"
+		eval "set -- $taropts"
+		if $verypoor
+		then	"$bzip" -d -k -c -- "$f" | \
+				"$tarprg" -x -v "$@" -f -
+		else	"$tarprg" -x -v $bzipflag "$@" -f "$f"
 		fi;;
-	s*)	if ${verypoor}
-		then	"${bzip}" -d -k -c -- "${f}" | \
-				"${tarprg}" -t ${verbose} -f -
-		else	"${tarprg}" -t ${verbose} ${bzipflag} -f "${f}"
+	s*)	if $verypoor
+		then	"$bzip" -d -k -c -- "$f" | \
+				"$tarprg" -t $verbose -f -
+		else	"$tarprg" -t $verbose $bzipflag -f "$f"
 		fi;;
-	t*)	"${bzip}" -t -v -- "${f}";;
+	t*)	"$bzip" -t -v -- "$f";;
 	esac || MyErr;;
 tar.lzma)
 	OptExternal lzma
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		if ${semipoor}
-		then	"${lzma}" -d -k -c -- "${f}" | \
-				"${tarprg}" -x -v "${@}" -f -
-		else	"${tarprg}" -x -v ${lzmaflag} "${@}" -f "${f}"
+		eval "set -- $taropts"
+		if $semipoor
+		then	"$lzma" -d -k -c -- "$f" | \
+				"$tarprg" -x -v "$@" -f -
+		else	"$tarprg" -x -v $lzmaflag "$@" -f "$f"
 		fi;;
-	s*)	if ${semipoor}
-		then	"${lzma}" -d -k -c -- "${f}" | \
-				"${tarprg}" -t ${verbose} -f -
-		else	"${tarprg}" -t ${verbose} ${lzmaflag} -f "${f}"
+	s*)	if $semipoor
+		then	"$lzma" -d -k -c -- "$f" | \
+				"$tarprg" -t $verbose -f -
+		else	"$tarprg" -t $verbose $lzmaflag -f "$f"
 		fi;;
-	t*)	"${lzma}" -t -v -- "${f}";;
+	t*)	"$lzma" -t -v -- "$f";;
 	esac || MyErr;;
 tar.xz)
 	OptExternal xz
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		if ${xzpoor}
-		then	"${xz}" -d -k -c -- "${f}" | \
-				"${tarprg}" -x -v "${@}" -f -
-		else	"${tarprg}" -x -v ${xzflag} "${@}" -f "${f}"
+		eval "set -- $taropts"
+		if $xzpoor
+		then	"$xz" -d -k -c -- "$f" | \
+				"$tarprg" -x -v "$@" -f -
+		else	"$tarprg" -x -v $xzflag "$@" -f "$f"
 		fi;;
-	s*)	if ${xzpoor}
-		then	"${xz}" -d -k -c -- "${f}" | \
-				"${tarprg}" -t ${verbose} -f -
-		else	"${tarprg}" -t ${verbose} ${xzflag} -f "${f}"
+	s*)	if $xzpoor
+		then	"$xz" -d -k -c -- "$f" | \
+				"$tarprg" -t $verbose -f -
+		else	"$tarprg" -t $verbose $xzflag -f "$f"
 		fi;;
-	t*)	"${xz}" -t -v -- "${f}";;
+	t*)	"$xz" -t -v -- "$f";;
 	esac || MyErr;;
 tar.lrz)
 	OptExternal lrzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
+		eval "set -- $taropts"
 		MkTemp && \
-			"${lrzip}" -d -o "${tempname}" -- "${f}" && \
-			"${tarprg}" -x -v "${@}" -f "${tempname}" && \
+			"$lrzip" -d -o "$tempname" -- "$f" && \
+			"$tarprg" -x -v "$@" -f "$tempname" && \
 			RmTemp \
 			|| MyErr;;
 	s*)	MkTemp && \
-			"${lrzip}" -d -o "${tempname}" -- "${f}" && \
-			"${tarprg}" -t ${verbose} -f "${tempname}" && \
+			"$lrzip" -d -o "$tempname" -- "$f" && \
+			"$tarprg" -t $verbose -f "$tempname" && \
 			RmTemp \
 			|| MyErr;;
 	t*)	MyErrNot;;
 	esac;;
 tar.7z)
 	OptExternal za 7za
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		eval "set -- ${taropts}"
-		"${za}" -so e -- "${f}" | "${tarprg}" -x -v "${@}" -f -;;
-	s*)	"${za}" -so e -- "${f}" | "${tarprg}" -t ${verbose} -f -;;
-	t*)	"${za}" t -- "${f}";;
+		eval "set -- $taropts"
+		"$za" -so e -- "$f" | "$tarprg" -x -v "$@" -f -;;
+	s*)	"$za" -so e -- "$f" | "$tarprg" -t $verbose -f -;;
+	t*)	"$za" t -- "$f";;
 	esac || MyErr;;
 gz)
 	OptExternal gzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		if ${mdir}
-		then	x="${name}.gz"
-			ln -s -- "${f}" "${x}" || cp -a -- "${f}" "${x}" \
-				&& "${gzip}" -d -N -f -- "${x}"
-		else	"${gzip}" -d -c -- "${f}" >"${pwdname}"
+		if $mdir
+		then	x=$name.gz
+			ln -s -- "$f" "$x" || cp -a -- "$f" "$x" \
+				&& "$gzip" -d -N -f -- "$x"
+		else	"$gzip" -d -c -- "$f" >"$pwdname"
 		fi;;
-	s*)	"${gzip}" -l -v -- "${f}";;
-	t*)	"${gzip}" -t -v -- "${f}";;
+	s*)	"$gzip" -l -v -- "$f";;
+	t*)	"$gzip" -t -v -- "$f";;
 	esac || MyErr;;
 bz2)
 	OptExternal bzip bzip2
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		if ${mdir}
-		then	x="${name}.gz"
-			ln -s -- "${f}" "${x}" || cp -a -- "${f}" "${x}" \
-				&& "${bzip}" -d -- "${x}"
-		else	"${bzip}" -d -k -c -- "${f}" >"${pwdname}"
+		if $mdir
+		then	x=$name.gz
+			ln -s -- "$f" "$x" || cp -a -- "$f" "$x" \
+				&& "$bzip" -d -- "$x"
+		else	"$bzip" -d -k -c -- "$f" >"$pwdname"
 		fi;;
-	s*)	"${bzip}" -l -v -- "${f}";;
-	t*)	"${bzip}" -t -v -- "${f}";;
+	s*)	"$bzip" -l -v -- "$f";;
+	t*)	"$bzip" -t -v -- "$f";;
 	esac || MyErr;;
 lzma)
 	OptExternal lzma
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		"${lzma}" -d -k -v -- "${f}" || MyErr;;
+		"$lzma" -d -k -v -- "$f" || MyErr;;
 	s*)	MyErrNot;;
-	t*)	"${lzma}" -t -v -- "${f}" || MyErr;;
+	t*)	"$lzma" -t -v -- "$f" || MyErr;;
 	esac;;
 xz)
 	OptExternal xz
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		"${xz}" -d -k -v -- "${f}" || MyErr;;
+		"$xz" -d -k -v -- "$f" || MyErr;;
 	s*)	MyErrNot;;
-	t*)	"${xz}" -t -v -- "${f}" || MyErr;;
+	t*)	"$xz" -t -v -- "$f" || MyErr;;
 	esac;;
 lrz)
 	OptExternal lrzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
-		if ${mdir}
-		then	"${lrzip}" -d -- "${f}"
-		else	"${lrzip}" -d -o "${pwdname}" -- "${f}"
+		if $mdir
+		then	"$lrzip" -d -- "$f"
+		else	"$lrzip" -d -o "$pwdname" -- "$f"
 		fi || MyErr;;
 	s*)	MyErrNot;;
 	t*)	MyErrNot;;
 	esac;;
 7z)
 	OptExternal za 7za
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x='x'
-		${junk} && x='e'
-		"${za}" ${x} -- "${f}";;
-	s*)	"${za}" l -- "${f}";;
-	t*)	"${za}" t -- "${f}";;
+		$junk && x='e'
+		"$za" $x -- "$f";;
+	s*)	"$za" l -- "$f";;
+	t*)	"$za" t -- "$f";;
 	esac || MyErr;;
 zip)
 	OptExternal unzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x=
-		eval set -- ${zipopts}
-		"${unzip}" "${@}" -- "${f}";;
+		eval set -- $zipopts
+		"$unzip" "$@" -- "$f";;
 	s*)	x='-l'
 		[ -n "${verbose:++}" ] && x='-v'
-		"${unzip}" ${x} -- "${f}";;
-	t*)	"${unzip}" -t -- "${f}";;
+		"$unzip" $x -- "$f";;
+	t*)	"$unzip" -t -- "$f";;
 	esac || MyErr;;
 arj)
 	OptExternal unarj
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x='x'
-		${junk} && x='e'
-		"${unarj}" ${x} -- "${f}";;
-	s*)	"${unarj}" l -- "${f}";;
-	t*)	"${unarj}" t -- "${f}";;
+		$junk && x='e'
+		"$unarj" $x -- "$f";;
+	s*)	"$unarj" l -- "$f";;
+	t*)	"$unarj" t -- "$f";;
 	esac || MyErr;;
 arj.gz)
 	OptExternal unarj
 	OptExternal gzip
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x='x'
-		${junk} && x='e'
+		$junk && x='e'
 		MkTemp && \
-			"${gzip}" -d -c -- "${f}" >"${tempname}" && \
-			"${unarj}" ${x} -- "${tempname}" && \
+			"$gzip" -d -c -- "$f" >"$tempname" && \
+			"$unarj" $x -- "$tempname" && \
 			RmTemp;;
 	s*)	MkTemp && \
-			"${gzip}" -d -c -- "${f}" >"${tempname}" && \
-			"${unarj}" l -- "${tempname}" && \
+			"$gzip" -d -c -- "$f" >"$tempname" && \
+			"$unarj" l -- "$tempname" && \
 			RmTemp;;
-	t*)	"${gzip}" -t -v -- "${f}" &&
+	t*)	"$gzip" -t -v -- "$f" &&
 			MkTemp && \
-			"${gzip}" -d -c -v -- "${f}" >"${tempname}" && \
-			"${unarj}" t -- "${tempname}" && \
+			"$gzip" -d -c -v -- "$f" >"$tempname" && \
+			"$unarj" t -- "$tempname" && \
 			RmTemp;;
 	esac || MyErr;;
 lha)
 	OptExternal lha
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x='-x'
-		${junk} || x='-xi'
-		"${lha}" ${x} -- "${f}";;
-	s*)	"${lha}" -v -- "${f}";;
-	t*)	"${lha}" -t -- "${f}";;
+		$junk || x='-xi'
+		"$lha" $x -- "$f";;
+	s*)	"$lha" -v -- "$f";;
+	t*)	"$lha" -t -- "$f";;
 	esac || MyErr;;
 rar)
 	OptExternal unrar
-	case ${mode} in
+	case $mode in
 	u*)	IntoDir || return
 		x='x'
-		${junk} && x='e'
-		"${unrar}" ${x} -- "${f}";;
+		$junk && x='e'
+		"$unrar" $x -- "$f";;
 	s*)	x='l'
 		[ -n "${verbose:++}" ] && x='vt'
-		"${unrar}" ${x} -- "${f}";;
-	t*)	"${unrar}" t -- "${f}";;
+		"$unrar" $x -- "$f";;
+	t*)	"$unrar" t -- "$f";;
 	esac || MyErr;;
 esac
 }
 
-MainLoop "${@}"
+MainLoop "$@"
 Exit
diff --git a/bin/zipd b/bin/zipd
--- a/bin/zipd
+++ b/bin/zipd
@@ -23,7 +23,7 @@ errbreak=false
 compat=false
 OPTIND=1
 while getopts 'FfdDkEhH?' opt
-do	case ${opt} in
+do	case $opt in
 	F)	symlink=:;;
 	d)	withparent=:
 		dotparent=false;;
@@ -35,48 +35,48 @@ do	case ${opt} in
 	*)	Usage 0;;
 	esac
 done
-shift $(( ${OPTIND} - 1 ))
-[ ${#} -ne 0 ] || Usage
+shift $(( $OPTIND - 1 ))
+[ $# -ne 0 ] || Usage
 
-${symlink} && Push zipopts '-y'
-${compat}  && Push zipopts '-k'
+$symlink && Push zipopts '-y'
+$compat  && Push zipopts '-k'
 
 MakeExternal zip zip
 
-d=${PWD}
+d=$PWD
 for argu
 do	stat=0
 	name=${argu%.zip}
 	name=${name%/}
-	Cd "${d}" || stat=${?}
-	if ! test -d "${name}"
+	Cd "$d" || stat=$?
+	if ! test -d "$name"
 	then	Err 1 "Could not find Directory $name"
 		continue
 	fi
-	Cd "${name}" || stat=${?}
-	zipfile="${d}/${name##*/}"
-	if ${compat}
-	then	zipfile="${zipfile}.ZIP"
-	else	zipfile="${zipfile}.zip"
+	Cd "$name" || stat=$?
+	zipfile=$d/${name##*/}
+	if $compat
+	then	zipfile=$zipfile.ZIP
+	else	zipfile=$zipfile.zip
 	fi
-	if test -r "${zipfile}"
-	then	Echo "removing old ${zipfile}"
-		rm -f -- "${zipfile}"
+	if test -r "$zipfile"
+	then	Echo "removing old $zipfile"
+		rm -f -- "$zipfile"
 	fi
-	if ${withparent}
-	then	[ ${stat} -eq 0 ] && Cd .. || stat=${?}
-		if ${dotparent}
+	if $withparent
+	then	[ $stat -eq 0 ] && Cd .. || stat=$?
+		if $dotparent
 		then	Push -c topack='.'
 		else	Push -c topack "${name##*/}"
 		fi
 	else	PushTopack || {
 			stat=2
-			Error ${stat} "not creating empty archive ${archive}"
+			Error $stat "not creating empty archive $archive"
 		}
 	fi
-	[ ${stat} -eq 0 ] && \
-		eval "\"\${zip}\" ${zipopts} \"\${zipfile}\" ${topack}" \
-		|| Error ${?} "Error when zipping ${name}"
+	[ $stat -eq 0 ] && \
+		eval "\"\$zip\" $zipopts \"\$zipfile\" $topack" \
+		|| Error $? "Error when zipping $name"
 done
 
 Exit
